🎉 Good Evening, Everyone!


I hope you're all doing great and having a wonderful start to your day!

Welcome to today’s session — we’re excited to have you here.

Today’s Agenda: Linear Algebra – Hands-on Session! ✍️📐
Get ready to dive into some exciting and practical concepts! 💡📊

Let’s wait for a few more minutes while everyone joins in.
Meanwhile, get your setup ready! 💬



#matrix
#matrix operations
#transpose
#det
#adj,inverse
#rank
#eigen values and vectors

In [ ]:
#create a matrix

import numpy as np

A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [ ]:
A +2

array([[3, 4],
       [5, 6]])

In [ ]:
A-2

array([[-1,  0],
       [ 1,  2]])

In [ ]:
A/2

array([[0.5, 1. ],
       [1.5, 2. ]])

In [ ]:
A*2

array([[2, 4],
       [6, 8]])

In [ ]:
B = np.array([[5,6],[7,8]])

In [ ]:
A+B

array([[ 6,  8],
       [10, 12]])

In [ ]:
A-B

array([[-4, -4],
       [-4, -4]])

In [ ]:
A*B

array([[ 5, 12],
       [21, 32]])

In [ ]:
A/B

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [ ]:
A

array([[1, 2],
       [3, 4]])

In [ ]:
C = np.array([[1,2],[4,5],[8,9]])
C

array([[1, 2],
       [4, 5],
       [8, 9]])

In [ ]:
A*C

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [ ]:
A

array([[1, 2],
       [3, 4]])

In [ ]:
#transpose
A.T

array([[1, 3],
       [2, 4]])

In [ ]:
A = np.array([[1,2,30],[4,5,6],[8,9,10]])
A

array([[ 1,  2, 30],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [ ]:
#det
np.linalg.det(A)

np.float64(-108.00000000000003)

In [ ]:
#inv
x = np.linalg.inv(A)
x

array([[ 0.03703704, -2.31481481,  1.27777778],
       [-0.07407407,  2.12962963, -1.05555556],
       [ 0.03703704, -0.06481481,  0.02777778]])

In [ ]:
y = np.round(x, 2)
y

array([[ 0.04, -2.31,  1.28],
       [-0.07,  2.13, -1.06],
       [ 0.04, -0.06,  0.03]])

In [ ]:
y = np.rint(x).astype(int)
y

array([[ 0, -2,  1],
       [ 0,  2, -1],
       [ 0,  0,  0]])

In [ ]:
#rank

A

array([[ 1,  2, 30],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [ ]:
np.linalg.matrix_rank(A)

np.int64(3)

In [ ]:
A

array([[ 1,  2, 30],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [ ]:
B = np.array([[1,2,3],[4,5,6]])
B.shape

(2, 3)

In [ ]:
np.linalg.matrix_rank(B)

np.int64(2)

In [ ]:
A

array([[ 1,  2, 30],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [ ]:
eig_val, eig_vec = np.linalg.eig(B)

LinAlgError: Last 2 dimensions of the array must be square

In [ ]:
eig_val

array([25.2255224 , -9.66834663,  0.44282423])

In [ ]:
eig_vec

array([[-0.74730261, -0.93763801,  0.72993389],
       [-0.32047526,  0.12264509, -0.68277009],
       [-0.58209485,  0.32525857,  0.03196129]])

In [ ]:
A

array([[ 1,  2, 30],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [ ]:
A*A

array([[  1,   4, 900],
       [ 16,  25,  36],
       [ 64,  81, 100]])

In [ ]:
from numpy.linalg import matrix_power

In [ ]:
matrix_power(A, 2)

array([[249, 282, 342],
       [ 72,  87, 210],
       [124, 151, 394]])

In [ ]:
A = np.array([[1,2],[3,4]])

In [ ]:
A

array([[1, 2],
       [3, 4]])

In [ ]:
A*A

array([[ 1,  4],
       [ 9, 16]])

In [ ]:
matrix_power(A, 2)

array([[ 7, 10],
       [15, 22]])