In [2]:
import numpy as np

In [3]:
a=int(input())
b=int(input())
c=int(input())
d=int(input())
A=int(input())
B=int(input())
C=int(input())
D=int(input())
m1=np.array([[a,b],[c,d]])
m2=np.array([[A,B],[C,D]])
print(m1)
print(m2)

 1
 2
 3
 4
 5
 6
 7
 8


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


#### addtion

In [4]:
m1+m2

array([[ 6,  8],
       [10, 12]])

#### subtraction

In [5]:
m1-m2

array([[-4, -4],
       [-4, -4]])

#### multipliction

In [6]:
m1*m2

array([[ 5, 12],
       [21, 32]])

In [9]:
def check_transpose(matrix):
    trans=matrix.T
    print(trans)
    if np.array_equal(matrix,trans):
        print("it is symmetric")
        print("____________________")
    elif np.array_equal(matrix,(-1)*trans):
        print("it is skew symmetric")
        print("____________________")
    else:
        print("it is non-symmertric")
        print("____________________") 
m3=np.array([[1, 2], [2, 1]])
m4= np.array([[0, 2], [-2, 0]])
check_transpose(m3)
check_transpose(m4)

[[1 2]
 [2 1]]
it is symmetric
____________________
[[ 0 -2]
 [ 2  0]]
it is skew symmetric
____________________


## 3rd question

In [16]:
A = np.array([[2, 5, 3],[4, 3, 3],[5, 6, 3]])

print(f"Matrix:{A}")
print(f"Determinant: {np.linalg.det(A)}")
print(f"Rank: {np.linalg.matrix_rank(A)}")

try:
    print(f"Inverse:{np.linalg.inv(A)}")
except np.linalg.LinAlgError:
    print("Inverse: Matrix is singular")

Matrix:[[2 5 3]
 [4 3 3]
 [5 6 3]]
Determinant: 23.999999999999993
Rank: 3
Inverse:[[-0.375       0.125       0.25      ]
 [ 0.125      -0.375       0.25      ]
 [ 0.375       0.54166667 -0.58333333]]


# 4th question

In [19]:
import numpy as np

# Test matrix
A = np.array([[2, 5, 3], [4, 3, 3], [5, 6, 3]])
w, v = np.linalg.eig(A)

print(f"Matrix A:{A}")
print(f"Eigenvalues (λ):{w}")
print(f"Eigenvectors (v):{v}")
fir_eigepai = np.allclose(A @ v[:, 0], w[0] * v[:, 0])
print(f"Verification of first eigenpair (A @ v ≈ λ * v): {fir_eigepai}")


Matrix A:[[2 5 3]
 [4 3 3]
 [5 6 3]]
Eigenvalues (λ):[11.08276253 -2.         -1.08276253]
Eigenvectors (v):[[-0.50950789 -0.80829038 -0.32863804]
 [-0.50950789  0.57735027 -0.32863804]
 [-0.6933999   0.11547005  0.8854344 ]]
Verification of first eigenpair (A @ v ≈ λ * v): True
