#HEY GUYS LET'S WAIT FOR EVERYONE TO JOIN THE SESSION
#WILL START THE SESSION AT 09:07


1. create a numpy array with numpy.array module and with a datatype integer and float.



In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5,6,7])
b = np.array([1.2,3.4,5,6,8.9])
print(a,a.dtype)
print(b,b.dtype)

[1 2 3 4 5 6 7] int64
[1.2 3.4 5.  6.  8.9] float64


2. create numpy array that have 0,1,2,3,4 dimensions respectively. also print their shape and dimensions of numpy arrays created above.

In [4]:
a = np.array(10)
print(a,a.ndim)

10 0


In [5]:
a = np.array([10])
print(a,a.ndim)

[10] 1


In [6]:
a = np.array([[10]])
print(a,a.ndim)

[[10]] 2


In [10]:
a = np.array([[[[1,2],[3,4],[7,8]]]])
print(a,a.ndim)

[[[[1 2]
   [3 4]
   [7 8]]]] 4


In [8]:
a = np.array([1,2,3,4,5,6])
b = a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


3. create a 2x3 , 3x3 and 4x4 identity matrix using numpy

In [15]:
x=np.eye(3,4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [13]:
y = np.identity(3)
y

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
y = np.identity(4)
y

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

4. create a numpy array with shape 2x5 that has all the elements as zero.

In [17]:
a=np.zeros((2,5),dtype='int32')
a


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

5. create a numpy array that has the shape 3x5 and all elements are 5.

In [19]:
y = np.full((3,5),0)
print(y)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


6. Create a numpy array with random integers in the range 0-100, and sample size should be 25.

In [21]:
ran=np.random.randint(0,101,(25))
ran

array([80, 78,  2, 17, 23, 16, 61, 42, 56, 40, 23, 44, 60, 81, 67,  6, 57,
        5, 54, 75, 86, 21, 46, 74,  4])

7. Create a numpy array with a shape 3x3 that has all elements as 1.

In [22]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


8. Create a numpy array in the shape 2x3 with random integers in the range 0 -100.
reshape the array in the shape 3x2 and print the updated shape of the resultant array.

In [23]:
x = np.random.randint(0,101,size=(2,3))
x

array([[59,  7,  1],
       [86,  1, 42]])

In [24]:
y =x.reshape((3,2))
y

array([[59,  7],
       [ 1, 86],
       [ 1, 42]])

9. create a random array , with the range 0 - 1000,with size 50.

In [25]:
x = np.random.randint(0,1001,size = 50)
x

array([901, 170, 726, 380, 768, 261, 451, 978, 763, 413, 493, 801, 501,
       489, 144, 161, 203, 147, 457, 589, 844, 579, 204, 640, 737, 616,
       995, 158, 999, 600, 807, 485, 363, 898, 714, 558, 475, 481, 511,
       312, 222, 710, 404, 243, 301, 590, 724, 182, 110, 847])

a. print the first ten elements of the array.

In [26]:
print(x[:10])

[901 170 726 380 768 261 451 978 763 413]


b. print the first ten elements of the array.

In [28]:
print(x[-10:])

[222 710 404 243 301 590 724 182 110 847]


c. print the elemnts from the index 10 to 25

In [29]:
print(x[10:26])

[493 801 501 489 144 161 203 147 457 589 844 579 204 640 737 616]


In [30]:
print(x[22])

204


10. given a numpy array that has valuues = [1,2,3,4,5].

In [31]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

insert the element 6 at the end of the array.

In [32]:
arr = np.append(arr,6) # append --> by default elements will get added at the end of the array.
arr

array([1, 2, 3, 4, 5, 6])

insert 10 at the beginning of the array.

In [34]:
arr = np.insert(arr,0,10)
arr

array([10,  1,  2,  3,  4,  5,  6])

insert the element 30, before 4.

In [35]:
arr = np.insert(arr,3,30)
arr

array([10,  1,  2, 30,  3,  4,  5,  6])

update the element 5 as 50.

In [48]:
arr[arr==5]=50
arr

TypeError: 'int' object does not support item assignment

Delete the element 50 in the updated array.

In [38]:
arr = np.delete(arr,np.where(arr==50))
print(arr)

[10  1  2 30  3  4  6]


TypeError: 'int' object is not subscriptable

sort the array in ascending order.

In [49]:
arr = np.sort(arr)
arr

AxisError: axis -1 is out of bounds for array of dimension 0