In [1]:
import numpy # it it executed without any error --> its already available in your machine

In [2]:
import xyz # xyz is random word --> so it will throw error

ModuleNotFoundError: No module named 'xyz'

In [4]:
import Numpy

ModuleNotFoundError: No module named 'Numpy'

In [5]:
import numppy

ModuleNotFoundError: No module named 'numppy'

In [3]:
ModuleNotFoundError
1. Case sensitive
2. Spelling mistake
3. Install your module --> pypi

ModuleNotFoundError

In [ ]:
# how to install module if its not available in machine (modulenotfound error)

In [7]:
pip install numpy # ! it does the installation via terminal 

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


## Numpy

In [ ]:
# convert list/tuple into an array

In [8]:
ar1 = numpy.array([1,2,3,4,5])
ar1

array([1, 2, 3, 4, 5])

In [9]:
type(ar1) # data structure for ar1 --> array

numpy.ndarray

In [11]:
numpy.array([1,2.4,'a']) # everything will be converted to higher data type
# U--> uni coded string # strings in numpy

array(['1', '2.4', 'a'], dtype='<U32')

In [ ]:
bool --> int --> float --> complex --> str 

In [12]:
numpy.array([1,2.4,2,3,4,5,6,7,8])

array([1. , 2.4, 2. , 3. , 4. , 5. , 6. , 7. , 8. ])

In [13]:
list1 = [1,2,3,4,5]
[i**2 for i in list1]

[1, 4, 9, 16, 25]

In [14]:
ar1**2

array([ 1,  4,  9, 16, 25])