#### Creating array

In [ ]:
# converting list/tuple

In [1]:
import numpy as np
ar1 = np.array([1,2,3,4,5])
ar1

array([1, 2, 3, 4, 5])

In [2]:
np.zeros([3,4]) #[3,4] --> shape # 1 parameter
# it creates an array of 3 rows and 4 columns with zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.random.random([3,4]) # shape parameter
# it creates array of 3 rows and 4 columns filled with random numbers in a range of 0 to 1

array([[0.54358373, 0.55238375, 0.29661809, 0.0910044 ],
       [0.06429496, 0.58191657, 0.22777022, 0.54571168],
       [0.91598055, 0.78887697, 0.24379434, 0.95194322]])

In [23]:
np.random.randint(0,10) # for every execution it gives random number in range of 0,10

5

In [29]:
np.random.randint(0,10,[3,4])

array([[0, 4, 7, 1],
       [3, 3, 7, 8],
       [2, 2, 3, 8]])

In [26]:
np.random.random((2,3))
# it creates array of 2 rows and 3 columns filled with random numbers in a range of 0 to 1

array([[0.37201014, 0.39391334, 0.86651609],
       [0.96512155, 0.0981605 , 0.44601588]])

#### Initiating an array

In [27]:
np.full([3,4], 10) # shape , value
# array of 3 rows and 4 columns and with a value 10

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [28]:
np.full([2,2], 'a') # U --> strings in numpy (unicoded strings)

array([['a', 'a'],
       ['a', 'a']], dtype='<U1')

In [30]:
range(0,5)

range(0, 5)

In [31]:
# end value is not included
for i in range(0,5):
    print(i, end= '')

01234

In [32]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [33]:
tuple(range(0,5))

(0, 1, 2, 3, 4)

In [34]:
list(range(0,10,2)) # start , end (not included ), skips(step-1)
# generate numbers from 0 till 10(excluding) by skipping (2-1) numbers

[0, 2, 4, 6, 8]

In [35]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [36]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
# help(np.arange)

In [38]:
np.linspace(0,10,6) # start , end (including), values 
# from 0 till 10 (including ) generate 6 numbers with equal difference 

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [41]:
np.linspace(0,20,4)

array([ 0.        ,  6.66666667, 13.33333333, 20.        ])

#### Analysing array

In [43]:
ar1 = np.arange(0,10)
ar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
ar1.dtype

dtype('int64')

In [ ]:
# VARCHAR(255), BIGINT, SMALLINT

# 64,32,1,20 --> python --> dynamically typed prog language --> assign data type on its own

In [46]:
# Attribute error:
# 1. spelling mistake 
# 2. case sensitive
# 3. Function doesnt exist

In [47]:
ar1.size # no. of elements

10

In [48]:
ar1.ndim # no.of dimensions

1

In [49]:
ar2 = np.arange(1,25)
ar2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [50]:
ar2.size

24

In [52]:
ar2 = ar2.reshape(6,4)
ar2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [53]:
ar2.shape

(6, 4)

In [54]:
ar2.ndim

2

In [55]:
ar2.reshape(5,5)
# 5*5 != 24 

ValueError: cannot reshape array of size 24 into shape (5,5)

In [56]:
ar2.reshape(3,3)
# 3*3 != 24 

ValueError: cannot reshape array of size 24 into shape (3,3)

In [57]:
ar2.reshape(3,2,4) # 3 sub arrays with 2 rows and 4 columns

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [58]:
ar2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [ ]:
# identify no.of elements in array using ar2.size
# now we can arrange it using reshape (rows * columns )
# product of rows and columns == size of array

In [59]:
ar3 = ar2.reshape(3,2,4)
ar3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [60]:
ar3.ndim

3

In [61]:
ar1 = np.arange(1,25).reshape(6,4)
ar1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [63]:
np.arange(1,25).reshape(6,4).shape

(6, 4)

#### Array Mathematics

In [64]:
ar1 = np.array([[10,20], [30,40]])
ar1

array([[10, 20],
       [30, 40]])

In [65]:
np.sum(ar1)

100

In [66]:
np.sum(ar1, axis = 0)

array([40, 60])

In [67]:
np.sum(ar1, axis = 1)

array([30, 70])

In [69]:
print(np.add(20,10))
print(np.subtract(20,10))
print(np.multiply(20,10))
print(np.divide(20,10))

30
10
200
2.0


In [70]:
print(np.log(20))
print(np.sqrt(20))
print(np.exp(20))
print(np.sin(20))

2.995732273553991
4.47213595499958
485165195.4097903
0.9129452507276277


In [71]:
ar1

array([[10, 20],
       [30, 40]])

In [72]:
print(np.min(ar1))

10


In [74]:
print(np.mean(ar1)) #average

25.0


In [75]:
print(np.max(ar1))

40
