In [6]:
import numpy as np

#### Slicing

In [7]:
ar1 = np.arange(1,25).reshape(6,4)
ar1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [2]:
ar2 = np.arange(1,10)
ar2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
ar2[3:7]

array([4, 5, 6, 7])

In [3]:
list1 = [1, 2, 3, 4, 5, 6, 7, 8, 9] # 4,5,6,7
# index will start from zero 
# end value is not included [start: end-1]
list1[3:7]

[4, 5, 6, 7]

In [4]:
ar1[2:5,1:3] # rows , columns # end value is not included # 5-1 , 4+1

array([[10, 11],
       [14, 15],
       [18, 19]])

In [8]:
ar1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [9]:
ar1[2:6,0:4]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [10]:
# If start value is not mentioned python will take 0 by default
ar1[2:6, :4]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [11]:
# if end value is not mentioned python executes till last (whatever is available at last)
ar1[2:6, 0:]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [12]:
ar1[2:, :]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [13]:
# if objective is to extract few rows with all the columns
ar1[2:] # if no value for columns mentioned it will extract all the columns

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [14]:
# if objective is to extract all the rows and few columns
ar1[:, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [15]:
ar1[:6]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [16]:
np.where(ar1 == 10) # row and column # is used to identify index of any value in array

(array([2]), array([1]))

#### Array Manipulation

In [17]:
ar1 = np.array([[10,20],[30,40]])
ar2 = np.array([[50,60],[70,80]])
ar2

array([[50, 60],
       [70, 80]])

In [18]:
np.concatenate([ar1,ar2], axis = 0) # axis = 0 --> perform concatenate operation on rows
# combine ar1 and ar2 at row level

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [19]:
np.row_stack([ar1,ar2])

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [20]:
np.vstack([ar1,ar2])

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [21]:
np.concatenate([ar1,ar2], axis = 1) # axis = 1 --> perform concatenation along columns

array([[10, 20, 50, 60],
       [30, 40, 70, 80]])

In [22]:
np.column_stack([ar1,ar2])

array([[10, 20, 50, 60],
       [30, 40, 70, 80]])

In [23]:
np.hstack([ar1,ar2])

array([[10, 20, 50, 60],
       [30, 40, 70, 80]])

In [24]:
ar3 = np.hstack([ar1,ar2,ar1])
ar3

array([[10, 20, 50, 60, 10, 20],
       [30, 40, 70, 80, 30, 40]])

In [25]:
np.hsplit(ar3, 3) # split array into 3 equal portions

[array([[10, 20],
        [30, 40]]),
 array([[50, 60],
        [70, 80]]),
 array([[10, 20],
        [30, 40]])]